mod 'puppetlabs/stdlib', '4.1.0'
mod 'puppetlabs/mysql',  '2.1.0'
mod 'puppetlabs/apt',    '1.4.0'
mod 'puppetlabs/nodejs', '0.4.0'

mod 'nodes/php',         '0.8.0'
mod 'jfryman/nginx',     '0.0.7'
mod 'ripienaar/concat',  '0.2.0'

mod 'phpmyadmin',
  :git => 'git://github.com/frastel/puppet-phpmyadmin',
  :ref => 'b66963cdaffd3f0787311bfb7cecd90cd2933db7'

mod 'phantomjs',
  :git => 'git://github.com/globin/puppet-phantomjs',
  :ref => 'c1cb3c6354e54dfa264d7e9dbd9382e1e8d090c2'
